

--1
SELECT DEPARTMENT_NAME, CATEGORY 
FROM TB_DEPARTMENT;

--2
SELECT DEPARTMENT_NAME|| '의 정원은 ' ||CAPACITY || '명 입니다' "학과별 정원"
FROM TB_DEPARTMENT ;

--3
SELECT STUDENT_NAME
FROM TB_DEPARTMENT
JOIN TB_STUDENT USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NO = '001' AND ABSENCE_YN = 'Y' AND SUBSTR(STUDENT_SSN,8,1) = '2';

--4
SELECT STUDENT_NAME 
FROM TB_STUDENT
WHERE STUDENT_NO IN ('A513079','A513090','A513091','A513110','A513119')
ORDER BY STUDENT_NAME DESC;

--5
SELECT DEPARTMENT_NAME, CATEGORY ,CAPACITY 
FROM TB_DEPARTMENT
WHERE CAPACITY >= 20 AND CAPACITY <= 30
ORDER BY DEPARTMENT_NAME ;

--6
SELECT PROFESSOR_NAME 
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

--7
SELECT STUDENT_NAME 
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;

--8
SELECT PREATTENDING_CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

--9
SELECT CATEGORY
FROM TB_DEPARTMENT
GROUP BY CATEGORY;

--10
SELECT STUDENT_NO, STUDENT_NAME , STUDENT_SSN, ABSENCE_YN,STUDENT_ADDRESS
FROM TB_STUDENT 
WHERE STUDENT_ADDRESS LIKE '%전주%'
AND ABSENCE_YN = 'N'
AND STUDENT_NO LIKE'A2%';