--1
SELECT STUDENT_NO "학번",STUDENT_NAME "이름", ENTRANCE_DATE "입학년도"
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NO = '002'
ORDER BY ENTRANCE_DATE ASC;

--2
SELECT PROFESSOR_NAME , PROFESSOR_SSN 
FROM TB_PROFESSOR
WHERE  LENGTH(PROFESSOR_NAME)!=3;

--3
SELECT PROFESSOR_NAME "교수이름", FLOOR(MONTHS_BETWEEN(SYSDATE, TO_DATE(SUBSTR(PROFESSOR_SSN, 1, 6))) /12)만나이
FROM TB_PROFESSOR 
WHERE SUBSTR(PROFESSOR_SSN,8,1)=1
ORDER BY PROFESSOR_SSN DESC;

--4
SELECT SUBSTR(PROFESSOR_NAME,2,2)"이름" 
FROM TB_PROFESSOR;

--5???????????????
SELECT STUDENT_NO , STUDENT_NAME 
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO,2,1)<=5
ORDER BY STUDENT_NO DESC;

--6
SELECT TO_CHAR(TO_DATE('2020-12-25', 'YYYY-MM-DD'), 'DAY') "2020년크리스마스"
FROM DUAL;

--7
SELECT TO_CHAR(TO_DATE('99/10/11', 'YY/MM/DD')),
		TO_CHAR(TO_DATE('49/10/11', 'YY/MM/DD')),
		TO_CHAR(TO_DATE('49/10/11', 'RR/MM/DD')),
		TO_CHAR(TO_DATE('49/10/11', 'RR/MM/DD'))
FROM DUAL;

--8
SELECT STUDENT_NO, STUDENT_NAME 
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO,1,1) != 'A';

--9
SELECT TRUNC(ROUND(AVG(POINT),1),1)"평점"
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
WHERE STUDENT_NO = 'A517178';

--10
SELECT D.DEPARTMENT_NO, COUNT(*)
FROM TB_DEPARTMENT D 
JOIN TB_STUDENT S ON (D.DEPARTMENT_NO =S.DEPARTMENT_NO)
GROUP BY D.DEPARTMENT_NO
ORDER BY D.DEPARTMENT_NO;

--11
SELECT  COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL
GROUP BY COACH_PROFESSOR_NO;

--12
SELECT TERM_NO, AVG(POINT)
FROM TB_STUDENT
JOIN TB_GRADE USING (STUDENT_NO)
WHERE TERM_NO LIKE '200%'
GROUP BY TERM_NO ;
